# Generated by Django 5.2.17 on 2026-09-21 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('assets', models.DecimalField(decimal_places=2, max_digits=14)),
                ('liabilities', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=14)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net_worth_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['snapshot_date'],
                'indexes': [models.Index(fields=['user', 'snapshot_date'], name='analytics_n_user_id_5f90c1_idx')],
                'unique_together': {('user', 'snapshot_date')},
            },
        ),
    ]
