# Generated by Django 5.2.17 on 2026-09-21 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('institution', models.CharField(blank=True, max_length=120)),
                ('account_type', models.CharField(choices=[('bank', 'Bank account'), ('cash', 'Cash'), ('credit_card', 'Credit card'), ('savings', 'Savings account'), ('wallet', 'Digital wallet'), ('investment', 'Investment account'), ('other', 'Other')], default='bank', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='PKR', max_length=8)),
                ('color', models.CharField(default='#1B7A4E', max_length=16)),
                ('icon', models.CharField(default='wallet', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('include_in_net_worth', models.BooleanField(default=True)),
                ('include_in_safe_to_spend', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('investment_type', models.CharField(choices=[('stock', 'Stock'), ('fund', 'Fund'), ('bond', 'Bond'), ('savings_cert', 'Savings certificate'), ('gold', 'Gold'), ('other', 'Other')], default='other', max_length=20)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('purchased_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='finance_accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_on'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transfer_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='finance_accounts.account')),
            ],
            options={
                'ordering': ['-transfer_date', '-id'],
            },
        ),
    ]
