# Generated by Django 5.2.17 on 2026-09-21 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='transactions.category'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'year', 'month'], name='budgets_bud_user_id_39ca25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together={('budget', 'category')},
        ),
    ]
